sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
#    access-key-id: LTAI5tCj24QABDw2N7vC1a6e
#    access-key-secret: y0g18JS51BPquKtRnSAMAclHPfMz1G
    bucket-name: sky-take-out-2025-3-2
